spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?autoReconnect=true&failOverReadOnly=false&useSSL=false&characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: yanyuqinghe
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      initial-size: 5
      max-wait-millis: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-while-idle: true
      test-on-return: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true
      cluster-name: my-application

